#application.yml
server.port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jooq.sql-dialect: MYSQL
  liquibase:
    change-log: classpath:db/migrations/db.changelog-master.yml
